sudo: required
services:
  - docker 

before_install:
  - docker build -t josheluis/docker-react -f Dockerfile.dev . 

script: 
  - docker run josheluis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-sa-east-1-614446127119"
  bucket_name: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"